#!/bin/bash

# Originally written by Ralf Kistner <ralf@embarkmobile.com>, but placed in the public domain

set +e

# If ANDROID_HOME is specified, use that adb; otherwise, search the path
if test ${ANDROID_HOME}; then
  : ${ADB:=${ANDROID_HOME}/platform-tools/adb}
else
  : ${ADB:=adb}
fi

bootanim=""
failcounter=0
timeout_in_sec=120

until [[ "$bootanim" =~ "stopped" ]]; do
  bootanim=`${ADB} -e shell getprop init.svc.bootanim 2>&1 &`
  if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
    || "$bootanim" =~ "running" ]]; then
    let "failcounter += 1"
    echo "Waiting for emulator to start"
    if [[ $failcounter -gt timeout_in_sec ]]; then
      echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
      exit 1
    fi
  fi
  sleep 1
done

echo "Emulator is ready"
